name: midya-website-app
region: tor
domains:
  - domain: midya.ca
    type: PRIMARY
  - domain: www.midya.ca
    type: ALIAS
static_sites:
  - name: midya-test-website
    github:
      repo: mrahmani-hash/midya-test-website
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: chmod +x build.sh && ./build.sh
    output_dir: _site
    index_document: index.html
    catchall_document: index.html
